<div id="ug-footer-global">
  <div class="container">
    <footer role="contentinfo" class="row navbar navbar-inverse">
      <div class="col-lg-12">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="//www.uoguelph.ca/accessibility/"><span class="fa fa-wheelchair"></span> Accessibility<span class="sr-only"> at University of Guelph</span></a></li>
          <li><a href="//www.uoguelph.ca/web/privacy/"><span class="fa fa-key"></span> Privacy <span class="sr-only"> at University of Guelph</span></a></li>
          <li><a href="//www.uoguelph.ca/sitemap/"><span class="fa fa-sitemap"></span> Site Map<span class="sr-only"> for University of Guelph</span></a></li>
          <li><a href="//www.uoguelph.ca/web/terms/">© University of Guelph</a></li>
        </ul>
      </div>
    </footer>
  </div>
</div>
<script type="text/javascript" src="https://ozplayer.global.ssl.fastly.net/3.3/ozplayer-core/ozplayer.free.js"></script>
<script type="text/javascript" src="https://ozplayer.global.ssl.fastly.net/3.3/ozplayer-lang/en.js"></script>
<script type="text/javascript" src="https://ozplayer.global.ssl.fastly.net/3.3/config.js"></script>
